// web/src/components/ExpenseRow.vue
<script setup lang="ts">
import AmountText from './AmountText.vue'
import TallyIcon from './TallyIcon.vue'

/** Tally's canonical glyph and hue per built-in category (spec §5). No emoji, ever. */
const CATEGORY_LOOK: Record<string, { icon: string; hue: number }> = {
  food: { icon: 'utensils', hue: 2 },
  drinks: { icon: 'beer', hue: 3 },
  transport: { icon: 'car-front', hue: 5 },
  stay: { icon: 'bed-double', hue: 7 },
  groceries: { icon: 'shopping-basket', hue: 4 },
  fun: { icon: 'ticket', hue: 8 },
  home: { icon: 'house', hue: 6 },
  other: { icon: 'circle-dashed', hue: 1 },
}

/**
 * One expense in a trip's feed: category disc, title, who paid, and your share.
 *
 * `allSquare` comes from the server's derived item state, not from comparing a balance to zero
 * here. It is square when every sharer's *approved* paybacks cover their portion, which is a
 * different question from whether your own share happens to be nil.
 */
const props = withDefaults(
  defineProps<{
    title: string
    categoryKey?: string
    paidBy?: string
    spentOn?: string
    yourShareMinor: number
    allSquare?: boolean
    currencyCode?: string
    symbol?: string
    divider?: boolean
  }>(),
  {
    categoryKey: 'other',
    paidBy: undefined,
    spentOn: undefined,
    allSquare: false,
    currencyCode: 'AUD',
    symbol: '$',
    divider: true,
  },
)

defineEmits<{ click: [] }>()

const look = () => CATEGORY_LOOK[props.categoryKey] ?? CATEGORY_LOOK.other!
const subtitle = () => [props.paidBy && `${props.paidBy} paid`, props.spentOn].filter(Boolean).join(' · ')
</script>

<template>
  <button type="button" class="row" :class="{ 'row--divided': divider }" @click="$emit('click')">
    <span
      class="row__disc"
      :style="{
        background: `var(--person-${look().hue})`,
        color: look().hue === 3 ? 'var(--ink)' : 'var(--text-on-accent)',
      }"
    >
      <TallyIcon :name="look().icon" :size="22" />
    </span>

    <span class="row__body">
      <span class="row__title">{{ title }}</span>
      <span class="row__subtitle">{{ subtitle() }}</span>
    </span>

    <span class="row__trailing">
      <AmountText
        :amount-minor="yourShareMinor"
        :currency-code="currencyCode"
        :symbol="symbol"
        :tone="allSquare ? 'settled' : yourShareMinor < 0 ? 'owe' : 'owed'"
        :show-sign="!allSquare"
      />
      <span class="row__caption">
        {{ allSquare ? 'settled' : yourShareMinor < 0 ? 'you owe' : 'you get' }}
      </span>
    </span>
  </button>
</template>

<style scoped>
.row {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  width: 100%;
  padding: 12px var(--space-4);
  min-height: 64px;
  background: transparent;
  border: none;
  cursor: pointer;
  text-align: left;
}

.row--divided {
  border-bottom: 1.5px solid var(--hairline);
}

.row:hover {
  background: var(--surface-card-hover);
}

.row__disc {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  flex: 0 0 auto;
  border: 2px solid var(--ink);
  border-radius: var(--radius-md);
}

.row__body {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-width: 0;
}

.row__title {
  font-family: var(--font-core);
  font-weight: var(--weight-bold);
  color: var(--ink);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.row__subtitle {
  font-size: var(--text-caption);
  color: var(--text-muted);
  margin-top: 2px;
}

.row__trailing {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 2px;
}

.row__caption {
  font-size: 11px;
  font-weight: var(--weight-bold);
  letter-spacing: 0.05em;
  text-transform: uppercase;
  color: var(--text-subtle);
}
</style>

// Tally_Design_System/components/lists/ExpenseRow.jsx
import React from 'react';
import { Icon } from '../core/Icon.jsx';
import { Amount } from '../core/Amount.jsx';
import { ListRow } from './ListRow.jsx';

const CAT_HUE = { food: 2, drinks: 3, transport: 5, stay: 7, groceries: 4, fun: 8, home: 6, other: 1 };
const CAT_ICON = { food: 'utensils', drinks: 'beer', transport: 'car-front', stay: 'bed-double', groceries: 'shopping-basket', fun: 'ticket', home: 'house', other: 'circle-dashed' };

/** One expense in a group feed: category disc, title, who paid, your share. */
export function ExpenseRow({ title, category = 'other', paidBy, date, yourShare = 0, settled, onClick, divider = true, style }) {
  const hue = CAT_HUE[category] || 1;
  return (
    <ListRow
      onClick={onClick}
      divider={divider}
      style={style}
      leading={
        <span style={{
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
          width: 44, height: 44, flex: '0 0 auto',
          background: `var(--person-${hue})`, border: '2px solid var(--ink)',
          borderRadius: 'var(--radius-md)', color: hue === 3 ? 'var(--ink)' : 'var(--text-on-accent)',
        }}>
          <Icon name={CAT_ICON[category] || 'circle-dashed'} size={22} />
        </span>
      }
      title={title}
      subtitle={[paidBy && `${paidBy} paid`, date].filter(Boolean).join(' · ')}
      trailing={
        <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 2 }}>
          <Amount value={yourShare} tone={settled ? 'settled' : yourShare < 0 ? 'owe' : 'owed'} showSign={!settled} />
          <span style={{ fontSize: 11, fontWeight: 'var(--weight-bold)', letterSpacing: '0.05em', textTransform: 'uppercase', color: 'var(--text-subtle)' }}>
            {settled ? 'settled' : yourShare < 0 ? 'you owe' : 'you get'}
          </span>
        </span>
      }
    />
  );
}
