// web/src/components/SplitBar.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import AmountText from './AmountText.vue'
import { splitShares } from '@/lib/split'

export interface SplitPerson {
  memberId: string
  displayName: string
  personHue: number
  /** A whole number. Not a percentage — percentages are floats, and these decide money. */
  weight: number
}

/**
 * The draggable proportional split, and Tally's signature interaction.
 *
 * Ported with the arithmetic changed. Tally's version keeps float percentages and multiplies them
 * back out to amounts; this one keeps **integer weights** and asks the same largest-remainder
 * routine the server uses. The amounts under the bar are therefore what the item will actually be
 * split into, to the cent, before it is saved — which is the whole reason the client mints the
 * item's id.
 */
const props = withDefaults(
  defineProps<{
    people: SplitPerson[]
    totalMinor: number
    /** The item's salt. Comes from its id, so the preview matches the server exactly. */
    salt: bigint
    currencyCode?: string
    symbol?: string
    height?: number
  }>(),
  { currencyCode: 'AUD', symbol: '$', height: 56 },
)

const emit = defineEmits<{ 'update:people': [SplitPerson[]] }>()

const bar = ref<HTMLElement | null>(null)
const dragging = ref<number | null>(null)

const totalWeight = computed(() => props.people.reduce((sum, p) => sum + p.weight, 0) || 1)

/** What each person actually pays. The engine's answer, not an approximation of it. */
const amounts = computed(() =>
  splitShares({
    totalMinor: props.totalMinor,
    weights: props.people.map((p) => p.weight),
    salt: props.salt,
  }),
)

const percents = computed(() => props.people.map((p) => (p.weight / totalWeight.value) * 100))

const edges = computed(() => {
  let running = 0
  return percents.value.slice(0, -1).map((p) => (running += p))
})

function beginDrag(index: number, event: PointerEvent) {
  event.preventDefault()
  dragging.value = index
  ;(event.target as Element).setPointerCapture?.(event.pointerId)
}

function endDrag() {
  dragging.value = null
}

function onMove(event: PointerEvent) {
  const index = dragging.value
  if (index === null || !bar.value) return

  const box = bar.value.getBoundingClientRect()
  const fraction = Math.min(1, Math.max(0, (event.clientX - box.left) / box.width))

  // The drag is converted to whole weights immediately. Holding a float and rounding at save time
  // is how a bar that reads 33/33/34 turns into something else entirely once it lands.
  const pairWeight = props.people[index]!.weight + props.people[index + 1]!.weight
  const before = props.people.slice(0, index).reduce((sum, p) => sum + p.weight, 0)
  const target = Math.round(fraction * totalWeight.value) - before

  // Nobody on the bar can be dragged to nothing: a person at zero owes nothing, which is a
  // different statement from a small share, and it should be made by removing them.
  const left = Math.min(Math.max(target, 1), pairWeight - 1)

  emit(
    'update:people',
    props.people.map((person, i) =>
      i === index
        ? { ...person, weight: left }
        : i === index + 1
          ? { ...person, weight: pairWeight - left }
          : person,
    ),
  )
}
</script>

<template>
  <div class="split" @pointermove="onMove" @pointerup="endDrag" @pointercancel="endDrag">
    <div ref="bar" class="split__bar" :style="{ height: `${height}px` }">
      <div
        v-for="(person, i) in people"
        :key="person.memberId"
        class="split__slice"
        :class="{ 'split__slice--still': dragging === null }"
        :style="{
          width: `${percents[i]}%`,
          background: `var(--person-${((person.personHue - 1) % 8) + 1})`,
          color: person.personHue === 3 ? 'var(--ink)' : 'var(--text-on-accent)',
        }"
      >
        <span v-if="(percents[i] ?? 0) > 12" class="split__percent">{{ Math.round(percents[i]!) }}%</span>
      </div>

      <span
        v-for="(edge, i) in edges"
        :key="`edge-${i}`"
        class="split__handle-hit"
        :style="{ left: `calc(${edge}% - 13px)` }"
        role="separator"
        :aria-label="`Adjust the split between ${people[i]?.displayName} and ${people[i + 1]?.displayName}`"
        @pointerdown="beginDrag(i, $event)"
      >
        <span class="split__handle" :class="{ 'split__handle--held': dragging === i }" />
      </span>
    </div>

    <div class="split__legend">
      <span v-for="(person, i) in people" :key="person.memberId" class="split__entry">
        <span
          class="split__dot"
          :style="{ background: `var(--person-${((person.personHue - 1) % 8) + 1})` }"
        />
        <span class="split__name">{{ person.displayName }}</span>
        <AmountText
          :amount-minor="amounts[i] ?? 0"
          :currency-code="currencyCode"
          :symbol="symbol"
          size="sm"
        />
      </span>
    </div>
  </div>
</template>

<style scoped>
.split__bar {
  position: relative;
  display: flex;
  width: 100%;
  border: 2px solid var(--ink);
  border-radius: var(--radius-md);
  overflow: hidden;
  box-shadow: 0 3px 0 0 var(--ink);
  background: var(--bg-sunk);
  touch-action: none;
  user-select: none;
}

.split__slice {
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

/* Only animates when nobody is dragging; easing a width under a moving thumb feels like lag. */
.split__slice--still {
  transition: width var(--dur-base) var(--ease-spring);
}

.split__percent {
  font-family: var(--font-money);
  font-size: 13px;
  font-weight: var(--weight-bold);
  white-space: nowrap;
}

.split__handle-hit {
  position: absolute;
  top: -2px;
  bottom: -2px;
  width: 26px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: ew-resize;
  touch-action: none;
}

.split__handle {
  width: 14px;
  height: 76%;
  border-radius: var(--radius-pill);
  background: var(--surface-card);
  border: 2px solid var(--ink);
  transition: transform var(--dur-fast) var(--ease-spring);
}

.split__handle--held {
  transform: scaleY(1.12) scaleX(1.15);
  box-shadow: var(--lift-drag);
}

.split__legend {
  display: flex;
  gap: var(--space-4);
  margin-top: var(--space-3);
  flex-wrap: wrap;
}

.split__entry {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.split__dot {
  width: 10px;
  height: 10px;
  border-radius: var(--radius-circle);
  border: 1.5px solid var(--ink);
}

.split__name {
  font-size: var(--text-caption);
  font-weight: var(--weight-semibold);
  color: var(--ink-2);
}
</style>

// Tally_Design_System/components/forms/SplitBar.jsx
import React from 'react';

/**
 * Draggable proportional split. One horizontal bar, one handle between each
 * neighbouring pair. This is Tally's signature interaction.
 */
export function SplitBar({ people = [], total = 100, onChange, height = 56, showLabels = true, style, ...rest }) {
  const ref = React.useRef(null);
  const [drag, setDrag] = React.useState(null);
  const sum = people.reduce((a, p) => a + (p.value || 0), 0) || 1;
  const pct = people.map((p) => ((p.value || 0) / sum) * 100);

  const move = (clientX) => {
    if (drag == null || !ref.current || !onChange) return;
    const r = ref.current.getBoundingClientRect();
    const at = Math.min(100, Math.max(0, ((clientX - r.left) / r.width) * 100));
    const before = pct.slice(0, drag).reduce((a, b) => a + b, 0);
    const pair = pct[drag] + pct[drag + 1];
    const left = Math.min(Math.max(at - before, 2), pair - 2);
    const next = people.map((p, i) =>
      i === drag ? { ...p, value: (left / 100) * sum }
      : i === drag + 1 ? { ...p, value: ((pair - left) / 100) * sum }
      : p
    );
    onChange(next);
  };

  React.useEffect(() => {
    if (drag == null) return;
    const mv = (e) => move(e.touches ? e.touches[0].clientX : e.clientX);
    const up = () => setDrag(null);
    window.addEventListener('pointermove', mv);
    window.addEventListener('pointerup', up);
    return () => { window.removeEventListener('pointermove', mv); window.removeEventListener('pointerup', up); };
  });

  let acc = 0;
  const edges = pct.slice(0, -1).map((p) => (acc += p));

  return (
    <div style={{ ...style }} {...rest}>
      <div
        ref={ref}
        style={{
          position: 'relative', display: 'flex', height, width: '100%',
          border: '2px solid var(--ink)', borderRadius: 'var(--radius-md)',
          overflow: 'hidden', boxShadow: '0 3px 0 0 var(--ink)', background: 'var(--bg-sunk)',
          touchAction: 'none', userSelect: 'none',
        }}
      >
        {people.map((p, i) => (
          <div key={p.name + i} style={{
            width: pct[i] + '%',
            background: `var(--person-${((p.hue || 1) - 1) % 8 + 1})`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            transition: drag == null ? 'width var(--dur-base) var(--ease-spring)' : 'none',
            overflow: 'hidden',
          }}>
            {pct[i] > 12 && (
              <span style={{
                fontFamily: 'var(--font-money)', fontSize: 13, fontWeight: 'var(--weight-bold)',
                color: (p.hue === 3) ? 'var(--ink)' : 'var(--text-on-accent)', whiteSpace: 'nowrap',
              }}>{Math.round(pct[i])}%</span>
            )}
          </div>
        ))}
        {edges.map((x, i) => (
          <span
            key={i}
            onPointerDown={(e) => { e.preventDefault(); setDrag(i); }}
            style={{
              position: 'absolute', top: -2, bottom: -2, left: `calc(${x}% - 13px)`,
              width: 26, display: 'flex', alignItems: 'center', justifyContent: 'center',
              cursor: 'ew-resize', touchAction: 'none',
            }}
          >
            <span style={{
              width: 14, height: height - 12, borderRadius: 'var(--radius-pill)',
              background: 'var(--surface-card)', border: '2px solid var(--ink)',
              transform: drag === i ? 'scaleY(1.12) scaleX(1.15)' : 'none',
              boxShadow: drag === i ? 'var(--lift-drag)' : 'none',
              transition: 'transform var(--dur-fast) var(--ease-spring)',
            }} />
          </span>
        ))}
      </div>
      {showLabels && (
        <div style={{ display: 'flex', gap: 'var(--space-4)', marginTop: 'var(--space-3)', flexWrap: 'wrap' }}>
          {people.map((p, i) => (
            <span key={p.name + i} style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
              <span style={{
                width: 10, height: 10, borderRadius: 'var(--radius-circle)',
                background: `var(--person-${((p.hue || 1) - 1) % 8 + 1})`, border: '1.5px solid var(--ink)',
              }} />
              <span style={{ fontSize: 'var(--text-caption)', fontWeight: 'var(--weight-semibold)', color: 'var(--ink-2)' }}>
                {p.name}
              </span>
              <span style={{
                fontFamily: 'var(--font-money)', fontVariantNumeric: 'tabular-nums',
                fontSize: 'var(--text-money-sm)', fontWeight: 'var(--weight-bold)', color: 'var(--ink)',
              }}>
                ${(((p.value || 0) / sum) * total).toFixed(2)}
              </span>
            </span>
          ))}
        </div>
      )}
    </div>
  );
}
