// Tally_Design_System/components/navigation/AppBar.jsx
import React from 'react';
import { IconButton } from '../core/IconButton.jsx';

/** Top bar. Title left-aligned and heavy; actions right. */
export function AppBar({ title, subtitle, onBack, actions, tone = 'paper', style, ...rest }) {
  const dark = tone === 'ink';
  return (
    <header
      style={{
        position: 'sticky', top: 0, zIndex: 20,
        display: 'flex', alignItems: 'center', gap: 'var(--space-2)',
        minHeight: 'var(--appbar-h)', padding: '8px var(--gutter-screen)',
        background: dark ? 'var(--ink)' : 'color-mix(in srgb, var(--paper) 88%, transparent)',
        backdropFilter: dark ? undefined : 'saturate(180%) blur(14px)',
        WebkitBackdropFilter: dark ? undefined : 'saturate(180%) blur(14px)',
        borderBottom: `2px solid ${dark ? 'var(--ink)' : 'var(--border-soft)'}`,
        color: dark ? 'var(--text-on-accent)' : 'var(--ink)',
        ...style,
      }}
      {...rest}
    >
      {onBack && <IconButton name="arrow-left" size={44} label="Back" onClick={onBack} style={{ marginLeft: -10, color: 'inherit' }} />}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{
          fontFamily: 'var(--font-core)', fontSize: 'var(--text-title)', fontWeight: 'var(--weight-black)',
          letterSpacing: 'var(--ls-title)', lineHeight: 1.1,
          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
        }}>{title}</div>
        {subtitle && (
          <div style={{ fontSize: 'var(--text-caption)', color: dark ? 'var(--ink-4)' : 'var(--text-muted)', marginTop: 1 }}>
            {subtitle}
          </div>
        )}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-1)' }}>{actions}</div>
    </header>
  );
}

// web/src/components/AppBar.vue
<script setup lang="ts">
import TallyIcon from './TallyIcon.vue'

withDefaults(defineProps<{ title: string; back?: boolean; action?: string }>(), {
  back: false,
  action: undefined,
})

defineEmits<{ back: []; action: [] }>()
</script>

<template>
  <header class="bar">
    <button v-if="back" type="button" class="bar__icon" aria-label="Back" @click="$emit('back')">
      <TallyIcon name="arrow-left" :size="22" />
    </button>
    <h1 class="bar__title">{{ title }}</h1>
    <button v-if="action" type="button" class="bar__icon" :aria-label="action" @click="$emit('action')">
      <TallyIcon :name="action" :size="22" />
    </button>
  </header>
</template>

<style scoped>
.bar {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-3) var(--space-4);
  background: var(--bg-app);
  border-bottom: 2px solid var(--ink);
  /* Sticks under the notch on a phone, which is where this app lives. */
  position: sticky;
  top: 0;
  padding-top: max(var(--space-3), env(safe-area-inset-top));
  z-index: 10;
}

.bar__title {
  flex: 1;
  min-width: 0;
  font-size: var(--text-heading-lg);
  font-weight: var(--weight-black);
  color: var(--ink);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.bar__icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  flex: 0 0 auto;
  background: var(--surface-card);
  border: 2px solid var(--ink);
  border-radius: var(--radius-circle);
  color: var(--ink);
  cursor: pointer;
}

.bar__icon:active {
  transform: translateY(2px);
}
</style>
