// Tally_Design_System/components/feedback/SettledBanner.jsx
import React from 'react';
import { Icon } from '../core/Icon.jsx';

/** The celebration moment: everyone is square. */
export function SettledBanner({ message = "You're all square", sub, style, ...rest }) {
  return (
    <div style={{
      position: 'relative', overflow: 'hidden',
      display: 'flex', alignItems: 'center', gap: 'var(--space-3)',
      padding: 'var(--pad-card-lg)', background: 'var(--mint)', color: 'var(--text-on-accent)',
      border: '2px solid var(--ink)', borderRadius: 'var(--radius-card)',
      boxShadow: '0 4px 0 0 var(--ink)',
      animation: 'tally-settle-pop var(--dur-celebrate) var(--ease-spring)',
      ...style,
    }} {...rest}>
      <span style={{
        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
        width: 44, height: 44, flex: '0 0 auto', background: 'var(--paper)', color: 'var(--mint-press)',
        border: '2px solid var(--ink)', borderRadius: 'var(--radius-circle)',
      }}>
        <Icon name="party-popper" size={24} />
      </span>
      <div>
        <div style={{ fontFamily: 'var(--font-core)', fontSize: 'var(--text-heading-lg)', fontWeight: 'var(--weight-black)', letterSpacing: 'var(--ls-heading-lg)' }}>
          {message}
        </div>
        {sub && <div style={{ fontSize: 'var(--text-caption)', opacity: 0.9, marginTop: 2 }}>{sub}</div>}
      </div>
      <style>{'@keyframes tally-settle-pop{0%{transform:scale(0.9) rotate(-1deg);opacity:0}60%{transform:scale(1.03) rotate(0.4deg)}100%{transform:scale(1) rotate(0);opacity:1}}'}</style>
    </div>
  );
}

// web/src/components/SettledBanner.vue
<script setup lang="ts">
import TallyIcon from './TallyIcon.vue'

/**
 * The moment a trip comes out square.
 *
 * Never a button and never a claim the app makes on its own behalf: it appears because every row
 * has been approved by the person owed (§7a). It celebrates a derived state, and if it is showing
 * when somebody is still owed money, the bug is upstream of here.
 */
withDefaults(defineProps<{ message?: string; sub?: string }>(), {
  message: "You're all square",
  sub: undefined,
})
</script>

<template>
  <div class="banner" role="status">
    <span class="banner__disc"><TallyIcon name="party-popper" :size="24" /></span>
    <span class="banner__text">
      <strong class="banner__message">{{ message }}</strong>
      <span v-if="sub" class="banner__sub">{{ sub }}</span>
    </span>
  </div>
</template>

<style scoped>
.banner {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-4);
  background: var(--mint);
  color: var(--text-on-accent);
  border: 2px solid var(--ink);
  border-radius: var(--radius-lg);
  box-shadow: 0 4px 0 0 var(--ink);
  animation: settle-pop var(--dur-base) var(--ease-spring);
}

@keyframes settle-pop {
  from {
    transform: scale(0.96);
    opacity: 0;
  }
}

@media (prefers-reduced-motion: reduce) {
  .banner {
    animation: none;
  }
}

.banner__disc {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  flex: 0 0 auto;
  background: var(--paper);
  color: var(--mint-press);
  border: 2px solid var(--ink);
  border-radius: var(--radius-circle);
}

.banner__text {
  display: flex;
  flex-direction: column;
}

.banner__message {
  font-size: var(--text-heading-sm);
  font-weight: var(--weight-black);
}

.banner__sub {
  font-size: var(--text-caption);
  opacity: 0.9;
  margin-top: 2px;
}
</style>
