// Tally_Design_System/components/navigation/TabBar.jsx
import React from 'react';
import { Icon } from '../core/Icon.jsx';

/** Bottom tab bar with a centre action slab. */
export function TabBar({ tabs = [], value, onChange, centerAction, style, ...rest }) {
  const half = Math.ceil(tabs.length / 2);
  const groups = centerAction ? [tabs.slice(0, half), tabs.slice(half)] : [tabs];
  const [down, setDown] = React.useState(false);

  const Tab = (t) => {
    const on = t.id === value;
    return (
      <button key={t.id} type="button" onClick={() => onChange && onChange(t.id)}
        style={{
          flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 3,
          minHeight: 'var(--tabbar-h)', border: 'none', background: 'transparent', cursor: 'pointer',
          color: on ? 'var(--action)' : 'var(--ink-4)',
          transition: 'color var(--dur-fast) var(--ease-out)',
        }}>
        <span style={{ transform: on ? 'translateY(-1px) scale(1.08)' : 'none', transition: 'transform var(--dur-fast) var(--ease-spring)' }}>
          <Icon name={t.icon} size={24} />
        </span>
        <span style={{ fontFamily: 'var(--font-core)', fontSize: 11, fontWeight: on ? 'var(--weight-black)' : 'var(--weight-semibold)', letterSpacing: '0.01em' }}>
          {t.label}
        </span>
      </button>
    );
  };

  return (
    <nav
      style={{
        position: 'sticky', bottom: 0, zIndex: 20,
        display: 'flex', alignItems: 'center',
        background: 'var(--surface-card)',
        borderTop: '2px solid var(--ink)',
        paddingBottom: 'var(--safe-bottom)',
        ...style,
      }}
      {...rest}
    >
      {groups[0].map(Tab)}
      {centerAction && (
        <button type="button" onClick={centerAction.onClick} aria-label={centerAction.label}
          onPointerDown={() => setDown(true)} onPointerUp={() => setDown(false)} onPointerLeave={() => setDown(false)}
          style={{
            flex: '0 0 auto', width: 60, height: 60, marginTop: -22,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: 'var(--action)', color: 'var(--text-on-accent)',
            border: '2.5px solid var(--ink)', borderRadius: 'var(--radius-circle)',
            boxShadow: `0 ${down ? 1 : 4}px 0 0 var(--ink)`,
            transform: down ? 'translateY(3px)' : 'none', cursor: 'pointer',
            transition: 'transform var(--dur-instant) var(--ease-out), box-shadow var(--dur-instant) var(--ease-out)',
          }}>
          <Icon name={centerAction.icon || 'plus'} size={30} />
        </button>
      )}
      {groups[1] && groups[1].map(Tab)}
    </nav>
  );
}

// web/src/components/TabBar.vue
<script setup lang="ts">
import TallyIcon from './TallyIcon.vue'

export interface Tab {
  id: string
  label: string
  icon: string
}

defineProps<{ tabs: Tab[]; modelValue: string }>()
defineEmits<{ 'update:modelValue': [string]; add: [] }>()
</script>

<template>
  <nav class="tabs">
    <button
      v-for="tab in tabs"
      :key="tab.id"
      type="button"
      class="tabs__tab"
      :class="{ 'tabs__tab--on': tab.id === modelValue }"
      :aria-current="tab.id === modelValue ? 'page' : undefined"
      @click="$emit('update:modelValue', tab.id)"
    >
      <TallyIcon :name="tab.icon" :size="24" />
      <span class="tabs__label">{{ tab.label }}</span>
    </button>
  </nav>
</template>

<style scoped>
.tabs {
  display: flex;
  align-items: stretch;
  background: var(--surface-card);
  border-top: 2px solid var(--ink);
  /* Clears the home indicator; without this the last tab sits under it. */
  padding-bottom: env(safe-area-inset-bottom);
}

.tabs__tab {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 3px;
  min-height: 56px;
  border: none;
  background: transparent;
  cursor: pointer;
  color: var(--ink-4);
  transition: color var(--dur-fast) var(--ease-out);
}

.tabs__tab--on {
  color: var(--action);
}

.tabs__tab--on :deep(.icon) {
  transform: translateY(-1px) scale(1.08);
  transition: transform var(--dur-fast) var(--ease-spring);
}

.tabs__label {
  font-size: 11px;
  font-weight: var(--weight-bold);
}
</style>
